### ISSUE TITLE
Installs empty egg

### ISSUE THREAD

**Issue by GoogleCodeExporter** [shenck0/py-leveldb#17]
```
What steps will reproduce the problem?
1../compile-leveldb.sh
2.python setup.py build
3.python setup.py install

What is the expected output? What do you see instead?
build outputs :
running build
running build_py
package init file '__init__.py' not found (or not a regular file)
package init file '__init__.py' not found (or not a regular file)
running build_ext

install outputs:
running install
running build
running build_py
package init file '__init__.py' not found (or not a regular file)
package init file '__init__.py' not found (or not a regular file)
running build_ext
running install_lib
running install_egg_info
Removing 
/home/oleiade/Dev/Envs/sandbox/lib/python2.7/site-packages/leveldb-0.1-py2.7.egg
-info
Writing 
/home/oleiade/Dev/Envs/sandbox/lib/python2.7/site-packages/leveldb-0.1-py2.7.egg
-info

when >>> import leveldb ; leveldb.LevelDB()
should shout, 'need a filename argument', got 
"""leveldb.LevelDB()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'LevelDB'"
instead

What version of the product are you using? On what operating system?
I'm using r48. Was working alright three, or four weeks ago...


```

Original issue reported on code.google.com by `tcre...@gmail.com` on 7 Jun 2012 at 1:07

**Comment by GoogleCodeExporter** [comment]
```
Nota : I'm using Python 2.7 in a virtualenv
```

Original comment by `tcre...@gmail.com` on 7 Jun 2012 at 1:13

**Comment by GoogleCodeExporter** [comment]
```
Works fine on 2.6, guess the problem comes from python2.7.
```

Original comment by `tcre...@gmail.com` on 7 Jun 2012 at 2:56

**Comment by GoogleCodeExporter** [comment]
```
[Fixed] Okay, sorry, this was due to a misconfiguration in my virtualenv.
```

Original comment by `tcre...@gmail.com` on 7 Jun 2012 at 3:40

**Comment by GoogleCodeExporter** [comment]
Original comment by `arnim...@gmail.com` on 7 Jun 2012 at 4:00
- Changed state: **Invalid**
